# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballClubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubname', models.CharField(max_length=250)),
                ('teamID', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_position', models.CharField(max_length=20)),
                ('player_name', models.CharField(max_length=250)),
                ('FootballClubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.FootballClubs')),
            ],
        ),
    ]
